rowa/Models/AccountModel.cs
using System.ComponentModel.DataAnnotations;

namespace rowa.Models
{
    public class AccountModel
    {
        [Required(ErrorMessage = "Email is required.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Password is required.")]
        public string Password { get; set; }
    }
}

rowa/Models/CreateRouteModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace rowa.Models
{
    public class CreateRouteModel
    {
        [DisplayName("Start Point"), Required]
        public string StartPoint { get; set; }

        [DisplayName("End Point"), Required]
        public string EndPoint { get; set; }

        [DisplayName("Way Points"), Required]
        public string WayPoints { get; set; }

        public string ErrorMessage { get; set; }
    }
}

rowa/Models/SignInModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace rowa.Models
{
    public class SignInModel
    {
        [Required(ErrorMessage = "Email is required.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Password is required.")]
        public string Password { get; set; }
    }
}

rowa/Controllers/AccountController.cs
using rowa.Models;
using rowa.repository.Classes;
using rowa.repository.Interfaces;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace rowa.Controllers
{
    public class AccountController : Controller
    {
        private IUserRepository _userRepository;
        private IUserHelper _userHelper;

        public AccountController(IUserRepository userRepository, IUserHelper userHelper)
        {
            _userRepository = userRepository;
            _userHelper = userHelper;
        }

        // GET: SignIn
        public ActionResult LogIn()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> LogIn(AccountModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("Index", model);
            }

            var userHasAuthenticated = await _userRepository.AuthenticateUser(model.Email, _userHelper.EncryptPassword(model.Password));

            if (userHasAuthenticated)
            {
                _userHelper.LogIn(model.Email);
                return RedirectToAction("Index", "Home");
            }

            ViewBag.ErrorMessage = "User name or password incorrect";

            return View("Index", model);
        }

        public ActionResult LogOut()
        {
            _userHelper.LogOut();

            return View();
        }
    }
}

rowa/Controllers/BrokenBeltRideController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace rowa.Controllers
{
    public class BrokenBeltRideController : Controller
    {
        
        public ActionResult RideInfo()
        {
            return View();
        }
    }
}

rowa/Controllers/ErrorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace rowa.Controllers
{
    public class ErrorController : Controller
    {
        // GET: Error
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult NotFound()
        {
            return View();
        }
    }
}

rowa/Controllers/HomeController.cs
using rowa.Filters;
using rowa.repository.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace rowa.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

rowa/Controllers/MemorialRideController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace rowa.Controllers
{
    public class MemorialRideController : Controller
    {
        // GET: MemorialRide
        public ActionResult MemorialRideInfo()
        {
            return View();
        }
    }
}

rowa/Controllers/RideRouteController.cs
using rowa.Filters;
using rowa.Models;
using rowa.repository.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace rowa.Controllers
{
    [UserInRole(RoleConsts.Admin)]
    public class RideRouteController : Controller
    {
        public ActionResult CreateRoute()
        {
            return View(new CreateRouteModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateRouteModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("CreateRoute", model);
            }

            var temp = model.WayPoints;

            ViewBag.SuccessMessage = "Successfully Created Route";

            return View("CreateRoute", model);
        }
    }
}

rowa/Controllers/SignInController.cs
using rowa.Models;
using rowa.repository.Classes;
using rowa.repository.Interfaces;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace rowa.Controllers
{
    public class SignInController : Controller
    {
        private IUserRepository _userRepository;
        private IUserHelper _userHelper;

        public SignInController(IUserRepository userRepository, IUserHelper userHelper)
        {
            _userRepository = userRepository;
            _userHelper = userHelper;
        }

        // GET: SignIn
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> LogIn(SignInModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("Index", model);
            }

            var userHasAuthenticated = await _userRepository.AuthenticateUser(model.Email, _userHelper.EncryptPassword(model.Password));

            if (userHasAuthenticated)
            {
                _userHelper.LogIn(model.Email);
                return RedirectToAction("Index", "Home");
            }

            ViewBag.ErrorMessage = "User name or password incorrect";

            return View("Index", model);
        }

        public ActionResult LogOut()
        {
            _userHelper.LogOut();

            return RedirectToAction("Index", "Home");
        }
    }
}

rowa/Controllers/TermsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace rowa.Controllers
{
    public class TermsController : Controller
    {
        // GET: Terms
        public ActionResult Terms()
        {
            return View();
        }
    }
}

rowa/Views/BrokenBeltRide/RideInfo.cshtml
@{
	ViewBag.Title = "RideInfo";
}

<h2>Broken Belt Ride</h2>

<div class="col-md-12">
	<p>In March 2013, ROWA set of to have an overnighter in Albany.</p>
	<p>Unfortunatly we would never make it.</p>
	<p>40 km's from Mount Barker and 300 km's from home, my final drive belt snapped.</p>
	<p>So now standing on the side of the Albany Highway in the pouring rain, I started making arrangements ti get the bike and myself back to Perth while the rest of the crew continued on.</p>
	<p>The rest of the crew were not allowing that. They refused to leave me there because we started together, they wanted us to finish together.</p>
	<p>Fortunately, I still had the original chain and sprockets in my shed at home. So my wife and step father loaded the car up and headed down to meet us.</p>
	<p>2 of the crew went on ahead to find somewhere for us to do the repair safely while I arranged a tow truck to get my bike there.</p>
	<p>They met the wonderful people at the Mount Barker Caravan Park who allowed us to turn their camp kitchen into a makeshift workshop for the night, where we stayed up until 2am the next morning making the repair.</p>
	<p>The next day we headed home and finished the ride together.</p>
	<p>This ride became the symbol of everything that ROWA is about and up holds our number 1 rule - NO ONE GETS LEFT BEHIND!</p>
	<p>In recognition of this we now hold the Broken Belt ride in March every year.</p>
	<p>We head back to stay with the awesome people at the Mount Barker Caravan Park and have some fun and laughs.</p>
</div>
<div class="row">
	<div class="col-md-6">
		<img src="~/Images/broken_belt.jpg" alt="broken_belt.jpg" class="img-width" />
	</div>
	<div class="col-md-6">
		<img src="~/Images/chain.jpg" alt="chain.jpg" class="img-width" />
	</div>
</div>
<br />
<div class="row">
	<div class="col-md-6">
		<img src="~/Images/bike_in_shed.jpg" alt="bike_in_shed.jpg" class="img-width" />
	</div>
	<div class="col-md-6">
		<img src="~/Images/working.jpg" alt="working.jpg" class="img-width" />
	</div>
</div>
<br />
<div class="row">
	<div class="col-md-12">
		<p>2 years later, on the 2015 BBR we decided that we should actually finish what we started and we did make it to Albany. Even if it was only for a coffee!</p>
		<img class="center-block img-width" src="~/Images/albany.jpg" alt="albany.jpg" />
	</div>
</div>
<div class="col-md-12">
	<h2>In 2019 we had our largest BBR turnout to date!</h2>
	<div class="row">
		<div class="col-md-6">
			<img src="~/Images/everyone_bbr.jpg" class="img-width" />
		</div>
		<div class="col-md-6">
			<img src="~/Images/sign_bbr.jpg" class="img-width" />
		</div>
	</div>
</div>

rowa/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>Riders of Western Australia</h2>

<div class="col-md-12">
	<p>
		Riders of Western Australia, or ROWA for short, is a group of motorcycling enthusiasts from all walks of life and on all types of bikes that get together for rides and to share their passion.
	</p>
	<p>
		ROWA was founded by Stewie Sutherland and the late Trevor "Woger Wabbit" Davis in 2012.
		Trevor and I started ROWA after some bad experiences with other groups.
		We decided we wanted a group that wasn't bike specific, free from politics and suitable to everyone.
	</p>
	<p>
		ROWA is not a club, association or organisation so there is no probation periods, joining fees, minimum requirement to join or any other rules you may find associated with clubs.
	</p>
	<p>
		We welcome everyone of all riding abilaties and pride ourselves on the experince and knowledge with have passed on to rookies and learners over the years.
		We have helped many learners gain experince and get their licenses and are more than happy to contiue helping people get into the wondful life of motorcycling.
	</p>
	<p>
		We invite anyone to join us and look forward to seeing you on a ride soon!
	</p>
	<p>
		<h2>**DISCLAIMER**</h2>
	</p>
	<p>
		Everyone is responsible for their own safety, and while we cannot control other motorists or road conditions, we can tell anybody who rides in a manner that is menacing, attracting the wrong attention or just plain dangerous to leave the group and feel free to never return. 
		MOTORCYCLE RIDING IS DANGEROUS and you ride with ROWA at your own risk.
	</p>
</div>

rowa/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>

<address>
    <strong>Email:</strong>   <a href="mailto:Support@example.com">ridersofwa@gmail.com</a>
</address>

rowa/Views/Home/Index.cshtml
@{
	ViewBag.Title = "Home Page";
}

<h2>Riders of Western Australia</h2>

<div class="row">
	<div class="col-md-6" style="padding-top: 100px">
		<p>Welcome to Riders of Western Australia.</p>
		<p>To join please go to the Terms of Membership page.</p>
		<p>Once you have read the terms and click the link at the bottom to be redirected to the Facebook Page.</p>
		<p>
			@Html.ActionLink("Terms of Membership", "Terms", "Terms", null, new { @class = "btn btn-primary" })
		</p>
	</div>
	<div class="col-md-6">
		<img src="~/Images/rowa_logo.jpg" alt="rowa.jpb" class="img-width" />
	</div>
</div>

<h3>Below are some pictures from some of our previous rides!</h3>
<div class="row">
	<div class="col-md-4">
		<img src="~/Images/3_bikes.jpg" alt="working.jpg" class="img-width" />
	</div>
	<div class="col-md-4">
		<img src="~/Images/bikes_ocean.jpg" alt="working.jpg" class="img-width" />
	</div>
	<div class="col-md-4">
		<img src="~/Images/bikes_narrogin.jpg" alt="working.jpg" class="img-width" />
	</div>
</div>

rowa/Views/MemorialRide/MemorialRideInfo.cshtml
@{
	ViewBag.Title = "MemorialRideInfo";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Trevor Davies Memorial Ride</h2>
<div class="col-md-12">
	<p>Trevor "Woger Wabbit" Davies was our Co-Founder and a very good friend.</p>
	<p>Tragically we lost Trev in May 2016 and to honor him and his unquestioned dedication to ROWA, we hold a memorial ride for him in May..</p>
	<p>Trev and I met some years before we started ROWA through other groups. We both had bad experiences with these groups and saw some of them be torn apart by politics and internal bickering.</p>
	<p>After experiencing this we decided we wanted to start our own group, free from politics and suitable for everyone from all walks of life, on all types of bikes.</p>
	<p>Trev was loved by all and hated by none. It was impossible to be unhappy when you where around him and his carefree nature was infectious.</p>
	<p>He was a loving husband, a devoted father and a great friend!</p>
</div>
<div class="row">
	<div class="col-md-4">
		<img src="~/Images/trev_wave_rock.jpg" alt="broken_belt.jpg" class="img-width" />
	</div>
	<div class="col-md-4">
		<img src="~/Images/trev_bikes.jpg" alt="chain.jpg" class="img-width" />
	</div>
	<div class="col-md-4">
		<img src="~/Images/trev_table.jpg" alt="bike_in_shed.jpg" class="img-width"/>
	</div>
</div>
<br />
<img src="~/Images/trev.jpg" alt="working.jpg" width="500" class="center" />
<br />
<h1 class="center">He will always be missed but never be forgotten.</h1>

rowa/Views/RideRoute/CreateRoute.cshtml
@model rowa.Models.CreateRouteModel

<h2>Create Ride Route</h2>

<div class="col-md-12">
    <span class="text-success">@ViewBag.SuccessMessage</span>
</div>

<div class="col-md-12">

    @using (Html.BeginForm("Create", "RideRoute", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            @Html.LabelFor(model => model.StartPoint)
            @Html.TextBoxFor(model => model.StartPoint, "", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.StartPoint, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            <label>Way Points</label>
            <input id="txtWayPoint" type="text" class="form-control" />
            <br />
            <button id="btnAdd" type="button" class="btn btn-primary" onclick="addItemToList()">Add</button>
            <ul id="ulWayPoints">
                @if (!string.IsNullOrWhiteSpace(Model.WayPoints))
                {
                    var points = Model.WayPoints.Split('+');

                    for (var i = 0; i < points.Length; i++)
                    {
                        <li id="@i">@points[i] <span title="Remove" class="glyphicon glyphicon-remove" onclick="removeFromList(@i)"></span></li>
                    }
                }
            </ul>
            @Html.HiddenFor(model => model.WayPoints)
            @Html.ValidationMessageFor(model => model.WayPoints, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.EndPoint)
            @Html.TextBoxFor(model => model.EndPoint, "", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.EndPoint, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    }
</div>

<script type="text/javascript">
    function addItemToList() {
        var ul = document.getElementById("ulWayPoints");
        var li = document.createElement("li");
        var textBox = document.getElementById("txtWayPoint");
        var input = document.getElementById("WayPoints");

        if (textBox.value !== "") {
            li.appendChild(document.createTextNode(textBox.value));
            ul.appendChild(li);

            if (input.value == "") {
                input.value = textBox.value;
            } else {
                input.value = input.value + "+" + textBox.value;
            }

            textBox.value = "";
        }
    }

    function removeFromList(id) {
        var li = document.getElementById(id);
        var input = document.getElementById("WayPoints");

        li.parentNode.removeChild(li);

        input.value = input.value.toString().replace(li.innerText, '');
    }
</script>

rowa/Views/Shared/_Layout.cshtml
@using rowa.repository.Classes
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Riders of Western Australia</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="site-colours">
    <div class="navbar navbar-inverse navbar-fixed-top navbar-colour">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Riders of Western Australia", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Trevor Davies Memorial", "MemorialRideInfo", "MemorialRide")</li>
                    <li>@Html.ActionLink("BBR (Broken Belt Ride)", "RideInfo", "BrokenBeltRide")</li>

                    @if (User.IsInRole(RoleConsts.Admin))
                    {
                        <li>@Html.ActionLink("Create Route", "CreateRoute", "RideRoute")</li>
                    }

                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Riders of Western Australia</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

rowa/Views/SignIn/Index.cshtml
@model rowa.Models.SignInModel

@{
	ViewBag.Title = "SignIn";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SignIn</h2>

<div class="col-md-12">
	<span class="text-danger">@ViewBag.ErrorMessage</span>
</div>

@using (Html.BeginForm("LogIn", "SignIn", FormMethod.Post))
{
	@Html.AntiForgeryToken()
	<div class="form-group">
		@Html.LabelFor(model => model.Email)
		<br />
		@Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
		@Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
	</div>
	<div class="form-group">
		@Html.LabelFor(model => model.Password)
		<br />
		@Html.PasswordFor(model => model.Password, new { @class = "form-control" })
		@Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
	</div>
	<div class="form-group">
		<button type="submit" class="btn btn-primary">Log In</button>
	</div>
}

rowa/Views/Terms/Terms.cshtml
@{
    ViewBag.Title = "Terms";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Terms of Membership</h2>

<div class="col-md-12">
	<p>Membership always has and always will be free!</p>
	<p>By joining Riders of Western Australia you agree to the following terms:</p>
	<ul>
		<li>You are responsible for your own safety and ride with ROWA at your own risk</li>
		<li>You are expected to hold a valid and appropriate license and also be insured with a minimum of 3rd party</li>
		<li>We are not a club, association or organization. We a group for people to share their passion for motorcycles</li>
		<li>We accept people from all walks of life on all types of bikes</li>
		<li>You have a motorcycle that is capable of doing at least 100 kph</li>
		<li>You will uphold our moto <strong>"No one gets left behind!"</strong></li>
		<li>You understand that we welcome suggestions but the group leaders (Stewie)  decision is final</li>
		<li>You will not ride or act in a matter that is dangerous to other group members or that will being negative attention to the group</li>
		<li>We can't allow outlaw colors, patches or insignia to worn on rides or at events</li>
		<li>Failure to up hold these terms may see you being ejected from the group</li>
	</ul>
	<p>If you agree to these Terms of Membership please click the button below to be redirected to our Facebook group.</p>
	<a href="https://www.facebook.com/groups/313568875504032/" class="btn btn-primary">Go To Facebook</a>
</div>